version: '3'

services:
    # db:
    #     image: postgres:10-alpine
    #     volumes:
    #         - pgdata:/data/postgres
    #     env_file:
    #         - ./.env.dev
    #     ports:
    #         - "5432:5432"
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        env_file:
            - ./.env.dev
        ports:
            - "5050:80"
        # depends_on:
        #     - db
volumes:
  pgdata: